// AUTO-GENERATED von K-Creative-Cloud/brand/piggy/tools/build.js — NICHT manuell bearbeiten.
// Quelle: brand/piggy/icons/sources.json (Feld "ionicons")
// Neu erzeugen: bash K-Creative-Cloud/brand/piggy/build.sh --sync

import type { PiggyIconName, PiggyIconMode } from './PiggyIcon';

/** Für die spätere Migration: Ionicons-Name → Piggy-Icon. "-outline" ⇒ outline, sonst filled. */
export const IONICONS_TO_PIGGY: Record<string, PiggyIconName> = {
  "home": "home",
  "home-outline": "home",
  "receipt": "receipt",
  "receipt-outline": "receipt",
  "folder": "folder",
  "folder-outline": "folder",
  "folder-open-outline": "folder",
  "person": "profile",
  "person-outline": "profile",
  "person-circle": "profile",
  "person-circle-outline": "profile",
  "bar-chart": "stats",
  "bar-chart-outline": "stats",
  "stats-chart": "stats",
  "settings": "settings",
  "settings-outline": "settings",
  "scan": "scan",
  "scan-outline": "scan",
  "camera": "camera",
  "camera-outline": "camera",
  "images": "gallery",
  "images-outline": "gallery",
  "image-outline": "gallery",
  "git-branch-outline": "split",
  "cut-outline": "split",
  "people": "friends",
  "people-outline": "friends",
  "person-add": "friend-add",
  "person-add-outline": "friend-add",
  "person-remove-outline": "friend-remove",
  "add": "add",
  "add-circle": "add-circle",
  "add-circle-outline": "add-circle",
  "share": "share",
  "share-outline": "share",
  "share-social-outline": "share",
  "paper-plane": "send",
  "paper-plane-outline": "send",
  "send": "send",
  "trash": "trash",
  "trash-outline": "trash",
  "pencil": "edit",
  "pencil-outline": "edit",
  "create-outline": "edit",
  "search": "search",
  "search-outline": "search",
  "filter": "filter",
  "filter-outline": "filter",
  "funnel-outline": "filter",
  "swap-vertical": "swap",
  "checkmark": "check",
  "checkmark-circle": "check-circle",
  "checkmark-circle-outline": "check-circle",
  "close": "close",
  "close-circle": "close-circle",
  "close-circle-outline": "close-circle",
  "alert-circle": "alert",
  "alert-circle-outline": "alert",
  "shield-checkmark": "shield-check",
  "shield-checkmark-outline": "shield-check",
  "chevron-back": "chevron-back",
  "chevron-forward": "chevron-forward",
  "chevron-down": "chevron-down",
  "arrow-up": "arrow-up",
  "arrow-down": "arrow-down",
  "card": "card",
  "card-outline": "card",
  "calendar": "calendar",
  "calendar-outline": "calendar",
  "qr-code": "qr-code",
  "qr-code-outline": "qr-code",
  "link": "link",
  "link-outline": "link",
  "log-out-outline": "logout",
  "cloud": "cloud",
  "cloud-outline": "cloud",
  "sparkles": "sparkles",
  "sparkles-outline": "sparkles",
  "document-attach-outline": "document",
  "document-outline": "document",
  "document-text-outline": "document",
  "key": "key",
  "key-outline": "key",
  "phone-portrait-outline": "phone",
  "pricetag": "tag",
  "pricetag-outline": "tag",
  "wallet": "wallet",
  "wallet-outline": "wallet",
  "cash-outline": "piggy-bank"
};

export function ioniconToPiggy(ion: string): { name: PiggyIconName; mode: PiggyIconMode } | null {
  const name = IONICONS_TO_PIGGY[ion];
  if (!name) return null;
  return { name, mode: ion.endsWith('-outline') ? 'outline' : 'filled' };
}
